services:
  api:
    build: ./BackgroundRemoverOfObject
    container_name: fastapi_api
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - ./BackgroundRemoverOfObject/.env

  bot:
    build: ./svgBot
    container_name: telegram_bot
    restart: always
    env_file:
      - ./svgBot/.env
    depends_on:
      - api
